### ISSUE TITLE
Add additional user information

### ISSUE THREAD

**Issue by slashplusweb** [bambamboole/laravel-cms#101]
While designing a bit, I wondered, why we don't have fields/columns for the following user information data:
- name
- lastname

Moreover I'd suggest to make the name unique as well, because a username should of course be unique, not just the email.

What do you think @bambamboole

**Comment by bambamboole** [comment]
name unique is ok. But I dont like the first name last name thingy.

**Comment by bambamboole** [comment]
I'll close this for now.
