### ISSUE TITLE
Correct readme regarding install

### ISSUE THREAD

**Issue by slashplusweb** [bambamboole/laravel-cms#3]
```
Command "cms:publish" is not defined.  
                                         
  Did you mean one of these?             
      cms:install
...
```
cli command probably should be `cms:install`, but is `cms:publish`

**Comment by bambamboole** [comment]
https://github.com/bambamboole/laravel-cms/blob/master/src/Commands/PublishCommand.php
It is publish. it was install, but currently it only publishes stuff. in future we maybe have a install command which does all this stuff in once. Tested PR welcome ;-)
