### ISSUE TITLE
Add optional featured image to the post

### ISSUE THREAD

**Issue by bambamboole** [bambamboole/laravel-cms#66]
Posts need an optional featured image. 
We may need to discuss how far we should go with cropping etc.

**Comment by slashplusweb** [comment]
where should this kind of data be stored in your opinion?
Id suggest to make either a seperated meta or a media table. this might also be required when implementing a media/gallery later.

**Comment by bambamboole** [comment]
in the first instance will simply save the file and to a folder and save the path to the model.
This will be resolved by #119 .
In Milestone 3 or 4 we will review the whole image process and implement a media library.

**Comment by bambamboole** [comment]
Done!
