### ISSUE TITLE
Role based access control

### ISSUE THREAD

**Issue by bambamboole** [bambamboole/laravel-cms#70]
We need roles and permissions.  
Let's discuss about how we implement it.

Maybe with [spatie/laravel-permission](https://github.com/spatie/laravel-permission) ?

**Comment by slashplusweb** [comment]
I just checked the laravel-permision implementation a bit and it looks very promising.

**Comment by bambamboole** [comment]
I also used this package once or twice and it is super powerful. the only thing is that the permissions are also stored in the database. But I am fine with this. We can discuss the handling on the wire :-)

**Comment by bambamboole** [comment]
If you use spatie permissions, you  may  copy the migration to  our migrations and  override the models with our own role and permission model

**Comment by bambamboole** [comment]
Ok this is merged now.
Next step would be to find a good convention to check the permissions.
